spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_cms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  redis:
    port: 6379
    host: 127.0.0.1
infomation:
  initialPassword: 123456
  token_prefix: token_%s
  expire: 7200
  token: token
  totalPage: 5
  pageNum: 5
  banStatus: 1
  nomalStatus: 0